version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - run: printenv CIRCLE_BRANCH
      - run: echo FOO

workflows:
  complicated:
    jobs:
      - build
      - build:
          name: build2
          requires:
            - build
  def:
    jobs:
      - build
  ghi:
    jobs:
      - build
