version: 2.1

  
jobs:
  xlarge-cache-persist-restore:
    docker:
      - image: cimb/base:current
    resource_class: xlarge
    steps:
    - checkout
    - run:
        name: Build file
        no_output_timeout: 30m
        command: |
           # Workaround the fact that wildcards/envs can't be used in cache paths
           mkdir /tmp/cache-entry
           head -c 8746586572 </dev/urandom > /tmp/cache-entry/cache-file-$CIRCLE_NODE_INDEX
    - save_cache:
        name: Saving xlarge file to cache
        key: v1-realitycheck-xlarge-file-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLE_BUILD_NUM }}-{{ .Environment.CIRCLE_NODE_INDEX }}
        paths:
         - /tmp/cache-entry
    - run:
         name: Delete xlarge file
         command: rm -rf /tmp/cache-entry
    - restore_cache:
        name: Restoring xlarge file from cache
        keys:
        - v1-realitycheck-xlarge-file-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLE_BUILD_NUM }}-{{ .Environment.CIRCLE_NODE_INDEX }}


workflows:
  main:
    jobs:
      - xlarge-cache-persist-restore
